### PR TITLE
feat(SwToggle): make v-model work properly on vue3

### PR DESCRIPTION
**Pull request by YossiSaadi**

### CODE REVIEW

**Comment by YossiSaadi** [comment]
@talkor 🤔 
image

**Comment by talkor** [comment]
> @talkor 🤔 image

try to delete node_modules and Vuepress' cache

**Comment by YossiSaadi** [comment]
> > @talkor 🤔 image
> 
> try to delete node_modules and Vuepress' cache

But it's on the CI, it doesn't related to the local state at my IDE 🙄

**Comment by talkor** [comment]
> > > @talkor 🤔 image
> > 
> > 
> > try to delete node_modules and Vuepress' cache
> 
> But it's on the CI, it doesn't related to the local state at my IDE 🙄

Oh that's weird, we already use it in some components

**Review by talkor — APPROVED** [review]
Awesome! Make sure it works with the recent changes :)

**Comment by talkor** [comment]
@YossiSaadi Merge?

**Comment by YossiSaadi** [comment]
> Yossi Saadi Merge?

tests are not working, I should get back to it this week

**Comment by talkor** [comment]
> > Yossi Saadi Merge?
> 
> tests are not working, I should get back to it this week

Ok, you need to update the branch, it was the issue with Vite that was fixed on the main branch

**Comment by YossiSaadi** [comment]
> > > Yossi Saadi Merge?
> > 
> > tests are not working, I should get back to it this week
> 
> Ok, you need to update the branch, it was the issue with Vite that was fixed on the main branch

Nope. It's the v-model issue with vitest or vue test utils, I can't remember which one we are using

**Comment by talkor** [comment]
@YossiSaadi do we still need it?

**Comment by YossiSaadi** [comment]
> @YossiSaadi do we still need it?

yes :( I'll need to make time to fix the tests

**Pull request closed without merging**
